### ISSUE TITLE
[Android] Failed to get FIS auth token

### ISSUE THREAD

**Issue by Kiruel** [infobip/mobile-messaging-flutter-plugin#22]
After init the SDK on the android platform like this:

```dart
InfobipMobilemessaging.init(Configuration(
      applicationCode: dotenv.get('INFOBIP_APPLICATION_CODE'),
      iosSettings: IOSSettings(
        notificationTypes: ['alert', 'badge', 'sound'],
        logging: true,
      ),
))
```

Got this error:
<details>
  <summary>Logs</summary>

```bash
/MobileMessagingFlutter(27333): onMethodCall: init
I/MobileMessagingFlutter(27333): activity: com.edenred.eq.uta.MainActivity@3e32c51
D/MobileMessagingFlutter(27333): init
D/CompatibilityChangeReporter(27333): Compat change id reported: 147600208; UID 10343; state: ENABLED
I/InAppChat(27333): Widget sync skipped. In-app chat is not activated or widget configuration is already synced
W/MobileMessaging(27333): Registration not available yet, will report user session later
2
W/MobileMessaging(27333): Registration is not available yet
I/InAppChat(27333): Widget sync skipped. In-app chat is not activated or widget configuration is already synced
W/MobileMessaging(27333): Registration not available yet, will patch messages later
W/MobileMessaging(27333): Registration not available yet, will report user session later
D/MobileMessagingFlutter(27333): StreamHandler.onListen: io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation@8bd2802
E/FirebaseMessaging(27333): Failed to get FIS auth token
E/FirebaseMessaging(27333): java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseMessaging(27333): 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.1.0:5)
E/FirebaseMessaging(27333): 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.1.0:9)
E/FirebaseMessaging(27333): 	at com.google.firebase.messaging.GmsRpc.setDefaultAttributesToBundle(GmsRpc.java:283)
E/FirebaseMessaging(27333): 	at com.google.firebase.messaging.GmsRpc.startRpc(GmsRpc.java:245)
E/FirebaseMessaging(27333): 	at com.google.firebase.messaging.GmsRpc.getToken(GmsRpc.java:195)
E/FirebaseMessaging(27333): 	at com.google.firebase.messaging.FirebaseMessaging.lambda$blockingGetToken$14$com-google-firebase-messaging-FirebaseMessaging(FirebaseMessaging.java:650)
E/FirebaseMessaging(27333): 	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda14.start(D8$$SyntheticClass:0)
E/FirebaseMessaging(27333): 	at com.google.firebase.messaging.RequestDeduplicator.getOrStartGetTokenRequest(RequestDeduplicator.java:67)
E/FirebaseMessaging(27333): 	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(FirebaseMessaging.java:646)
E/FirebaseMessaging(27333): 	at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$7$com-google-firebase-messaging-FirebaseMessaging(FirebaseMessaging.java:421)
E/FirebaseMessaging(27333): 	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda11.run(D8$$SyntheticClass:0)
E/FirebaseMessaging(27333): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
E/FirebaseMessaging(27333): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/FirebaseMessaging(27333): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
E/FirebaseMessaging(27333): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/FirebaseMessaging(27333): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/FirebaseMessaging(27333): 	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.3.0:2)
E/FirebaseMessaging(27333): 	at java.lang.Thread.run(Thread.java:1012)
E/FirebaseMessaging(27333): Caused by: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseMessaging(27333): 	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:154)
E/FirebaseMessaging(27333): 	at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:533)
E/FirebaseMessaging(27333): 	at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:387)
E/FirebaseMessaging(27333): 	at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$3$com-google-firebase-installations-FirebaseInstallations(FirebaseInstallations.java:372)
E/FirebaseMessaging(27333): 	at com.google.firebase.installations.FirebaseInstallations$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
E/FirebaseMessaging(27333): 	at com.google.firebase.concurrent.SequentialExecutor$1.run(SequentialExecutor.java:117)
E/FirebaseMessaging(27333): 	at com.google.firebase.concurrent.SequentialExecutor$QueueWorker.workOnQueue(SequentialExecutor.java:229)
E/FirebaseMessaging(27333): 	at com.google.firebase.concurrent.SequentialExecutor$QueueWorker.run(SequentialExecutor.java:174)
E/FirebaseMessaging(27333): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/FirebaseMessaging(27333): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/FirebaseMessaging(27333): 	at com.google.firebase.concurrent.CustomThreadFactory.lambda$newThread$0$com-google-firebase-concurrent-CustomThreadFactory(CustomThreadFactory.java:47)
E/FirebaseMessaging(27333): 	at com.google.firebase.concurrent.CustomThreadFactory$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
E/FirebaseMessaging(27333): 	... 1 more

/FirebaseRegistrationTokenHandler(27333): Error while acquiring token
E/FirebaseRegistrationTokenHandler(27333): java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(FirebaseMessaging.java:665)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$7$com-google-firebase-messaging-FirebaseMessaging(FirebaseMessaging.java:421)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda11.run(D8$$SyntheticClass:0)
E/FirebaseRegistrationTokenHandler(27333): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
E/FirebaseRegistrationTokenHandler(27333): 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/FirebaseRegistrationTokenHandler(27333): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
E/FirebaseRegistrationTokenHandler(27333): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/FirebaseRegistrationTokenHandler(27333): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.3.0:2)
E/FirebaseRegistrationTokenHandler(27333): 	at java.lang.Thread.run(Thread.java:1012)
E/FirebaseRegistrationTokenHandler(27333): Caused by: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.1.0:5)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.1.0:9)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(FirebaseMessaging.java:663)
E/FirebaseRegistrationTokenHandler(27333): 	... 9 more
E/FirebaseRegistrationTokenHandler(27333): Caused by: java.io.IOException: FIS_AUTH_ERROR
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.firebase.messaging.GmsRpc.handleResponse(GmsRpc.java:332)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.firebase.messaging.GmsRpc.lambda$extractResponseWhenComplete$0$com-google-firebase-messaging-GmsRpc(GmsRpc.java:343)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.firebase.messaging.GmsRpc$$ExternalSyntheticLambda0.then(D8$$SyntheticClass:0)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.1.0:3)
E/FirebaseRegistrationTokenHandler(27333): 	at androidx.profileinstaller.ProfileInstallReceiver$$ExternalSyntheticLambda0.execute(D8$$SyntheticClass:0)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.1.0:1)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.1.0:5)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.1.0:3)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.1.0:8)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.cloudmessaging.zzy.execute(Unknown Source:0)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.1.0:1)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.1.0:5)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.1.0:3)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@18.1.0:1)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.cloudmessaging.zzs.zzd(com.google.android.gms:play-services-cloud-messaging@@17.2.0:3)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.cloudmessaging.zzu.zza(com.google.android.gms:play-services-cloud-messaging@@17.2.0:2)
E/FirebaseRegistrationTokenHandler(27333): 	at com.google.android.gms.cloudmessaging.zzm.handleMessage(com.google.android.gms:play-services-cloud-messaging@@17.2.0:14)
E/FirebaseRegistrationTokenHandler(27333): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/FirebaseRegistrationTokenHandler(27333): 	at android.os.Looper.loopOnce(Looper.java:230)
E/FirebaseRegistrationTokenHandler(27333): 	at android.os.Looper.loop(Looper.java:319)
E/FirebaseRegistrationTokenHandler(27333): 	at android.app.ActivityThread.main(ActivityThread.java:8918)
E/FirebaseRegistrationTokenHandler(27333): 	at java.lang.reflect.Method.invoke(Native Method)
E/FirebaseRegistrationTokenHandler(27333): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/FirebaseRegistrationTokenHandler(27333): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```
</details>

And on iOS got no problem with the init and could send push notification, so not related to the ID client. I also follow the tuto for the server secret file to put on android side.

**Comment by Kiruel** [comment]
I find the problem, it was on the GCP sha1 restriction. I close this.
